#!/bin/sh

python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/576k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch576k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/208k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch208k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/304k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch304k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/160k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch160k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/256k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch256k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/554k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch554k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/448k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch448k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/112k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch112k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/496k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch496k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/352k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch352k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/400k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch400k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/64k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch64k.npz --tta_level 8 --batch_size 1 --block_size 220
python ./../waifu2x.py --gpu 0 --method noise --noise_level 0 --input /nfs/ug/thesis/thesis0/mkccgrp/input_gpu_test --arch VGG7 --output ../oralPresentation/16k_96x96_gpuTest --model_dir ./epoch --model_name flickrFaces_300x300_epoch16k.npz --tta_level 8 --batch_size 1 --block_size 220

read Wait